[package]
name = "genkey-impact-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4.0"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "^1.0", features = ["derive"] }
tokio = { version = "^1.0", features = ["full"] }
